/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 06a104859b54b1975b4d94e4ac8e4e42)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "Database" | "SyncedStateServer" | "RealtimeDurableObject";
	}
	interface Env {
		BETTER_AUTH_URL: string;
		BETTER_AUTH_SECRET: string;
		GITHUB_CLIENT_SECRET: string;
		GITHUB_CLIENT_ID: string;
		DATABASE: DurableObjectNamespace<import("./src/worker").Database>;
		STATE_COORDINATOR: DurableObjectNamespace /* SyncedStateServer */;
		REALTIME_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").RealtimeDurableObject>;
		AVATAR_BUCKET: R2Bucket;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_URL" | "BETTER_AUTH_SECRET" | "GITHUB_CLIENT_SECRET" | "GITHUB_CLIENT_ID">> {}
}
