/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 957099091a7d72982fcf05e0c45170db)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "Database" | "RealtimeDurableObject" | "LogoAgentContainer" | "SvgConverterContainer" | "AgentSession";
	}
	interface Env {
		BETTER_AUTH_URL: string;
		BETTER_AUTH_SECRET: string;
		GITHUB_CLIENT_SECRET: string;
		GITHUB_CLIENT_ID: string;
		CHROMA_API_TOKEN: string;
		CHROMA_TENANT: string;
		CHROMA_DATABASE: string;
		CLOUDFLARE_API_TOKEN: string;
		CLOUDFLARE_API_KEY: string;
		CLOUDFLARE_ACCOUNT_ID: string;
		ANTHROPIC_API_KEY: string;
		ADMIN_API_KEY: string;
		FIRECRAWL_API_KEY: string;
		GOOGLE_AI_API_KEY: string;
		DATABASE: DurableObjectNamespace<import("./src/worker").Database>;
		REALTIME_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").RealtimeDurableObject>;
		LOGO_AGENT: DurableObjectNamespace<import("./src/worker").LogoAgentContainer>;
		SVG_CONVERTER: DurableObjectNamespace<import("./src/worker").SvgConverterContainer>;
		AGENT_SESSION: DurableObjectNamespace<import("./src/worker").AgentSession>;
		AVATAR_BUCKET: R2Bucket;
		LOGOS_BUCKET: R2Bucket;
		UPLOADS_BUCKET: R2Bucket;
		LOGO_INGESTION_QUEUE: Queue;
		AI: Ai;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_URL" | "BETTER_AUTH_SECRET" | "GITHUB_CLIENT_SECRET" | "GITHUB_CLIENT_ID" | "CHROMA_API_TOKEN" | "CHROMA_TENANT" | "CHROMA_DATABASE" | "CLOUDFLARE_API_TOKEN" | "CLOUDFLARE_API_KEY" | "CLOUDFLARE_ACCOUNT_ID" | "ANTHROPIC_API_KEY" | "ADMIN_API_KEY" | "FIRECRAWL_API_KEY" | "GOOGLE_AI_API_KEY">> {}
}
