/**
 * Agent State Types and Phase Enums
 *
 * This module defines the core types for the logo generation agent workflow.
 * The agent progresses through phases: discovery → research → concept → refinement → export
 */

/**
 * Agent workflow phases
 */
export type AgentPhase =
  | 'discovery'
  | 'research'
  | 'concept'
  | 'refinement'
  | 'export';

/**
 * Approval status for user gates between phases
 */
export type ApprovalStatus =
  | 'pending'
  | 'approved'
  | 'rejected'
  | 'approved_with_changes';

/**
 * Types of actions logged in agent history
 */
export type AgentActionType =
  | 'user_input'
  | 'agent_action'
  | 'judge_evaluation'
  | 'approval'
  | 'tool_call'
  | 'error'
  | 'phase_transition';

/**
 * Brand discovery data gathered in the discovery phase
 */
export interface BrandDiscoveryData {
  brandName: string;
  industry: string;
  targetAudience: string;
  brandPersonality: string[]; // e.g., ['modern', 'playful', 'professional']
  competitors: string[];
  colorPreferences: string[];
  stylePreferences: string[]; // e.g., ['minimalist', 'geometric', 'organic']
  additionalNotes: string;
  completenessScore: number; // 0-100, judge-evaluated
}

/**
 * Research result from Firecrawl web scraping
 */
export interface ResearchResult {
  id: string;
  sourceUrl: string;
  sourceType: 'competitor' | 'inspiration' | 'trend';
  title: string;
  description: string;
  imageUrls: string[];
  extractedPatterns: string[]; // Design patterns identified
  relevanceScore: number; // 0-100, judge-evaluated
}

/**
 * Style attributes for a logo concept
 */
export interface ConceptStyleAttributes {
  type: string; // 'wordmark', 'lettermark', 'icon', etc.
  shapes: string[];
  colors: string[];
  mood: string;
}

/**
 * Logo concept generated by Google AI
 */
export interface ConceptData {
  id: string;
  description: string; // Text description of concept
  previewImageUrl: string; // Google AI generated preview
  previewImageBase64?: string; // For inline display
  designRationale: string; // Why this concept fits the brand
  styleAttributes: ConceptStyleAttributes;
  approvalStatus: ApprovalStatus;
  userFeedback?: string;
  judgeEvaluation?: JudgeEvaluation;
}

/**
 * SVG version generated from JavaScript code execution
 */
export interface SVGVersion {
  id: string;
  conceptId: string;
  svg: string;
  jsCode: string; // The JS that generated this SVG
  iterationNumber: number;
  approvalStatus: ApprovalStatus;
  userFeedback?: string;
  judgeEvaluation?: JudgeEvaluation;
}

/**
 * Judge evaluation scores
 */
export interface JudgeScores {
  brandAlignment: number; // 0-10
  visualQuality: number; // 0-10
  technicalValidity: number; // 0-10
  distinctiveness: number; // 0-10
}

/**
 * Judge evaluation result from AI evaluators
 */
export interface JudgeEvaluation {
  passed: boolean;
  scores: JudgeScores;
  overallScore: number; // Average of scores
  reasoning: string;
  suggestions: string[]; // Actionable improvement suggestions
  criticalIssues: string[]; // Must-fix issues
}

/**
 * Approval request awaiting user response
 */
export interface ApprovalRequest {
  phase: AgentPhase;
  items: ApprovalItem[];
  requestedAt: string;
}

/**
 * Item pending approval
 */
export interface ApprovalItem {
  id: string;
  type: 'brandInfo' | 'research' | 'concept' | 'svg';
  description: string;
  previewUrl?: string;
}

/**
 * Action logged in agent history
 */
export interface AgentAction {
  id: string;
  timestamp: string;
  phase: AgentPhase;
  type: AgentActionType;
  data: Record<string, unknown>;
}

/**
 * Iteration counts per phase
 */
export interface IterationCounts {
  discovery: number;
  research: number;
  concept: number;
  refinement: number;
  export: number;
}

/**
 * Complete agent state persisted in Durable Object
 */
export interface AgentState {
  sessionId: string;
  userId: string;
  phase: AgentPhase;
  brandInfo: BrandDiscoveryData;
  researchResults: ResearchResult[];
  concepts: ConceptData[];
  selectedConceptId: string | null;
  svgVersions: SVGVersion[];
  currentSvgVersionId: string | null;
  awaitingApproval: ApprovalRequest | null;
  history: AgentAction[];
  iterationCounts: IterationCounts;
  createdAt: string;
  updatedAt: string;
}

/**
 * Default brand discovery data for new sessions
 */
export function createDefaultBrandInfo(): BrandDiscoveryData {
  return {
    brandName: '',
    industry: '',
    targetAudience: '',
    brandPersonality: [],
    competitors: [],
    colorPreferences: [],
    stylePreferences: [],
    additionalNotes: '',
    completenessScore: 0,
  };
}

/**
 * Default iteration counts for new sessions
 */
export function createDefaultIterationCounts(): IterationCounts {
  return {
    discovery: 0,
    research: 0,
    concept: 0,
    refinement: 0,
    export: 0,
  };
}

/**
 * Create a new agent state for a session
 */
export function createAgentState(sessionId: string, userId: string): AgentState {
  const now = new Date().toISOString();
  return {
    sessionId,
    userId,
    phase: 'discovery',
    brandInfo: createDefaultBrandInfo(),
    researchResults: [],
    concepts: [],
    selectedConceptId: null,
    svgVersions: [],
    currentSvgVersionId: null,
    awaitingApproval: null,
    history: [],
    iterationCounts: createDefaultIterationCounts(),
    createdAt: now,
    updatedAt: now,
  };
}

/**
 * Create an agent action for logging
 */
export function createAgentAction(
  phase: AgentPhase,
  type: AgentActionType,
  data: Record<string, unknown>
): AgentAction {
  return {
    id: crypto.randomUUID(),
    timestamp: new Date().toISOString(),
    phase,
    type,
    data,
  };
}
